import type { GetStaticPaths, GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { markdownToHtml } from '../../libs/markdown/converters'
import { getAllPosts, getPostBySlug } from '../../libs/markdownPosts'
import styles from '../../styles/Home.module.css'

const Home: NextPage = (props) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <pre><code>{JSON.stringify(props, null,2)}</code></pre>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home

export const getStaticPaths:GetStaticPaths = async () => {
    const slugs = getAllPosts()

    return {
        paths: slugs.map(slug => ({
            params: {
                slug: Array.isArray(slug) ? slug.join('/') :slug
            }
        })),
        fallback: 'blocking'
    }
}

export const getStaticProps: GetStaticProps = async ({params}) => {
    console.log({params})
    // @ts-expect-error
    const post = getPostBySlug('blog/' + params.slug, ['date', 'title', 'content'])
  return {
    props: {
        post: {
            ...post,
            content: await markdownToHtml(post.content as any)
          }
    }
  }
}